
# Adduce template stylesheet and new one
style = ["config/assets/txc.css", "config/assets/lib.css"]
# mobile support
head = ["config/assets/mobile.html", "config/assets/favicon.html"]
# main holds the body of the document in main there are blocks which have properties
[main]


# title

[[main.block]]
from_str = "config/global/title.md"
style = "md"

# Main site info
[[main.block]]
from_str = "config/index/about.md"
style = "md"

# footer 
[[main.block]]
from_str = "config/assets/footer.html"
style = "html"
